"""add_user_changepoint_table

Revision ID: 2ea7fcf67853
Revises: f2a3b4c5d6e7
Create Date: 2026-06-18 01:06:30.285621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2ea7fcf67853'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_changepoint',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.Date(), nullable=False),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('changepoint_date', sa.Date(), nullable=True),
    sa.Column('signal', sa.String(length=50), nullable=True),
    sa.Column('factor_key', sa.String(length=100), nullable=True),
    sa.Column('analysis_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_method IN ('daily_correlation', 'before_after')", name='chk_analysis_method'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_changepoint_id'), 'user_changepoint', ['id'], unique=False)
    op.create_index('ix_user_changepoint_user_detected', 'user_changepoint', ['user_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_changepoint_user_detected', table_name='user_changepoint')
    op.drop_index(op.f('ix_user_changepoint_id'), table_name='user_changepoint')
    op.drop_table('user_changepoint')
    # ### end Alembic commands ###
