"""add_food_item_seed

Revision ID: 3f3f552a5810
Revises: 673e01960af2
Create Date: 2026-05-28 17:49:05.137025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.dialects import mysql


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return any(idx['name'] == index_name for idx in sa_inspect(conn).get_indexes(table_name))

# revision identifiers, used by Alembic.
revision: str = '3f3f552a5810'
down_revision: Union[str, Sequence[str], None] = '673e01960af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    if not _index_exists(conn, 'agent_result', 'ix_agent_result_id'):
        op.create_index(op.f('ix_agent_result_id'), 'agent_result', ['id'], unique=False)
    op.alter_column('analysis_request', 'lookback_days',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'14'"))
    if not _index_exists(conn, 'analysis_request', 'ix_analysis_request_id'):
        op.create_index(op.f('ix_analysis_request_id'), 'analysis_request', ['id'], unique=False)
    if not _index_exists(conn, 'analysis_result', 'ix_analysis_result_id'):
        op.create_index(op.f('ix_analysis_result_id'), 'analysis_result', ['id'], unique=False)
    op.alter_column('cosmetic_ingredients', 'comedogenic',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('daily_behavior_log', 'sleep_quality',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('daily_behavior_log', 'stress_level',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    if not _index_exists(conn, 'daily_behavior_log', 'ix_daily_behavior_log_id'):
        op.create_index(op.f('ix_daily_behavior_log_id'), 'daily_behavior_log', ['id'], unique=False)
    if not _index_exists(conn, 'diet_log', 'ix_diet_log_id'):
        op.create_index(op.f('ix_diet_log_id'), 'diet_log', ['id'], unique=False)
    if not _index_exists(conn, 'diet_log_item', 'ix_diet_log_item_id'):
        op.create_index(op.f('ix_diet_log_item_id'), 'diet_log_item', ['id'], unique=False)
    op.alter_column('environment_log', 'humidity',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('environment_log', 'uv_index',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    if not _index_exists(conn, 'environment_log', 'ix_environment_log_id'):
        op.create_index(op.f('ix_environment_log_id'), 'environment_log', ['id'], unique=False)
    if not _index_exists(conn, 'food_item', 'ix_food_item_id'):
        op.create_index(op.f('ix_food_item_id'), 'food_item', ['id'], unique=False)
    op.alter_column('medication_ingredient', 'is_skin_relevant',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('skin_log', 'overall_score',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    if not _index_exists(conn, 'skin_log', 'ix_skin_log_id'):
        op.create_index(op.f('ix_skin_log_id'), 'skin_log', ['id'], unique=False)
    op.alter_column('user_baseline', 'avg_reaction_delay',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    if not _index_exists(conn, 'user_baseline', 'ix_user_baseline_id'):
        op.create_index(op.f('ix_user_baseline_id'), 'user_baseline', ['id'], unique=False)
    if not _index_exists(conn, 'user_factor_sensitivity', 'ix_user_factor_sensitivity_id'):
        op.create_index(op.f('ix_user_factor_sensitivity_id'), 'user_factor_sensitivity', ['id'], unique=False)
    if not _index_exists(conn, 'user_location', 'ix_user_location_id'):
        op.create_index(op.f('ix_user_location_id'), 'user_location', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    if _index_exists(conn, 'user_location', 'ix_user_location_id'):
        op.drop_index(op.f('ix_user_location_id'), table_name='user_location')
    if _index_exists(conn, 'user_factor_sensitivity', 'ix_user_factor_sensitivity_id'):
        op.drop_index(op.f('ix_user_factor_sensitivity_id'), table_name='user_factor_sensitivity')
    if _index_exists(conn, 'user_baseline', 'ix_user_baseline_id'):
        op.drop_index(op.f('ix_user_baseline_id'), table_name='user_baseline')
    op.alter_column('user_baseline', 'avg_reaction_delay',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    if _index_exists(conn, 'skin_log', 'ix_skin_log_id'):
        op.drop_index(op.f('ix_skin_log_id'), table_name='skin_log')
    op.alter_column('skin_log', 'overall_score',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    op.alter_column('medication_ingredient', 'is_skin_relevant',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    if _index_exists(conn, 'food_item', 'ix_food_item_id'):
        op.drop_index(op.f('ix_food_item_id'), table_name='food_item')
    if _index_exists(conn, 'environment_log', 'ix_environment_log_id'):
        op.drop_index(op.f('ix_environment_log_id'), table_name='environment_log')
    op.alter_column('environment_log', 'uv_index',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    op.alter_column('environment_log', 'humidity',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    if _index_exists(conn, 'diet_log_item', 'ix_diet_log_item_id'):
        op.drop_index(op.f('ix_diet_log_item_id'), table_name='diet_log_item')
    if _index_exists(conn, 'diet_log', 'ix_diet_log_id'):
        op.drop_index(op.f('ix_diet_log_id'), table_name='diet_log')
    if _index_exists(conn, 'daily_behavior_log', 'ix_daily_behavior_log_id'):
        op.drop_index(op.f('ix_daily_behavior_log_id'), table_name='daily_behavior_log')
    op.alter_column('daily_behavior_log', 'stress_level',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    op.alter_column('daily_behavior_log', 'sleep_quality',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('cosmetic_ingredients', 'comedogenic',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    if _index_exists(conn, 'analysis_result', 'ix_analysis_result_id'):
        op.drop_index(op.f('ix_analysis_result_id'), table_name='analysis_result')
    if _index_exists(conn, 'analysis_request', 'ix_analysis_request_id'):
        op.drop_index(op.f('ix_analysis_request_id'), table_name='analysis_request')
    op.alter_column('analysis_request', 'lookback_days',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'14'"))
    if _index_exists(conn, 'agent_result', 'ix_agent_result_id'):
        op.drop_index(op.f('ix_agent_result_id'), table_name='agent_result')
    # ### end Alembic commands ###
