"""add preprocessed photo url columns to skin_log

Revision ID: 6ac0047d9828
Revises: af39a86dc089
Create Date: 2026-06-17 20:33:08.835787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ac0047d9828'
down_revision: Union[str, Sequence[str], None] = 'af39a86dc089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_log', sa.Column('masked_photo_url', sa.String(length=500), nullable=True))
    op.add_column('skin_log', sa.Column('left_photo_url', sa.String(length=500), nullable=True))
    op.add_column('skin_log', sa.Column('right_photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skin_log', 'right_photo_url')
    op.drop_column('skin_log', 'left_photo_url')
    op.drop_column('skin_log', 'masked_photo_url')
    # ### end Alembic commands ###
