"""add_concern_verdict_fields

Revision ID: c2402749c6ce
Revises: d3e4f5a6b7c8
Create Date: 2026-06-16 15:00:47.331108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c2402749c6ce'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_request', sa.Column('suspected_factors', sa.JSON(), nullable=True))
    op.add_column('analysis_request', sa.Column('concern_note', sa.Text(), nullable=True))
    op.add_column('analysis_result', sa.Column('concern_verdicts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_result', 'concern_verdicts')
    op.drop_column('analysis_request', 'concern_note')
    op.drop_column('analysis_request', 'suspected_factors')
    # ### end Alembic commands ###
