"""Add fields to PendingCosmeticProduct

Revision ID: d3e3027a0b1d
Revises: e957d1a7ee44
Create Date: 2026-07-01 17:26:28.626804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3e3027a0b1d'
down_revision: Union[str, Sequence[str], None] = 'e957d1a7ee44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.add_column('pending_cosmetic_products', sa.Column('ingredients_text', sa.Text(), nullable=True))
    op.add_column('pending_cosmetic_products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('pending_cosmetic_products', sa.Column('source_note', sa.Text(), nullable=True))
    op.add_column('pending_cosmetic_products', sa.Column('reject_reason', sa.Text(), nullable=True))
    op.add_column('pending_cosmetic_products', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('pending_cosmetic_products', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'pending_cosmetic_products', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_cosmetic_products', type_='foreignkey')
    op.drop_column('pending_cosmetic_products', 'reviewed_at')
    op.drop_column('pending_cosmetic_products', 'reviewed_by')
    op.drop_column('pending_cosmetic_products', 'reject_reason')
    op.drop_column('pending_cosmetic_products', 'source_note')
    op.drop_column('pending_cosmetic_products', 'image_url')
    op.drop_column('pending_cosmetic_products', 'ingredients_text')
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
