"""add_period_log_and_user_location_and_avg_cycle_length

Revision ID: e55b759be60d
Revises: 73d66c3f8679
Create Date: 2026-06-02 16:28:46.003621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e55b759be60d'
down_revision: Union[str, Sequence[str], None] = '73d66c3f8679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_log_id'), 'period_log', ['id'], unique=False)
    op.create_index(op.f('ix_period_log_user_id'), 'period_log', ['user_id'], unique=False)
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.add_column('users', sa.Column('avg_cycle_length', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avg_cycle_length')
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_period_log_user_id'), table_name='period_log')
    op.drop_index(op.f('ix_period_log_id'), table_name='period_log')
    op.drop_table('period_log')
    # ### end Alembic commands ###
