"""Add PendingCosmeticProduct

Revision ID: e957d1a7ee44
Revises: f8ca11ed0b2a
Create Date: 2026-07-01 15:42:18.190223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e957d1a7ee44'
down_revision: Union[str, Sequence[str], None] = 'f8ca11ed0b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_cosmetic_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_cosmetic_products_id'), 'pending_cosmetic_products', ['id'], unique=False)
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.create_index(op.f('ix_food_item_canonical_id'), 'food_item', ['canonical_id'], unique=False)
    op.add_column('medication_ingredient', sa.Column('english_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_ingredient', 'english_name')
    op.drop_index(op.f('ix_food_item_canonical_id'), table_name='food_item')
    op.alter_column('cosmetic_products', 'ingredients',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_pending_cosmetic_products_id'), table_name='pending_cosmetic_products')
    op.drop_table('pending_cosmetic_products')
    # ### end Alembic commands ###
