"""baseline_luvel_schema

Revision ID: f8ca11ed0b2a
Revises:
Create Date: 2026-07-01 13:06:48.090832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f8ca11ed0b2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmetic_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('english_name', sa.Text(), nullable=True),
    sa.Column('cas_no', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('is_irritant', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('restriction_limit', sa.String(length=255), nullable=True),
    sa.Column('comedogenic', sa.SmallInteger(), nullable=True),
    sa.Column('comedogenic_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosmetic_ingredients_id'), 'cosmetic_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_cosmetic_ingredients_name'), 'cosmetic_ingredients', ['name'], unique=True)
    op.create_table('cosmetic_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('ingredients', sa.Text(length=16777215), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_product_id', sa.String(length=100), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosmetic_products_brand'), 'cosmetic_products', ['brand'], unique=False)
    op.create_index(op.f('ix_cosmetic_products_id'), 'cosmetic_products', ['id'], unique=False)
    op.create_index(op.f('ix_cosmetic_products_normalized_name'), 'cosmetic_products', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_cosmetic_products_product_name'), 'cosmetic_products', ['product_name'], unique=False)
    op.create_table('food_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_food_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbohydrate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sugar', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sodium', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('raw_material_text', sa.Text(), nullable=True),
    sa.Column('allergen_text', sa.Text(), nullable=True),
    sa.Column('skin_factors', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('caffeine', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('glycemic_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('serving_size', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('serving_unit', sa.String(length=20), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('canonical_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_id'], ['food_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_item_api_food_code'), 'food_item', ['api_food_code'], unique=True)
    op.create_index(op.f('ix_food_item_barcode'), 'food_item', ['barcode'], unique=False)
    op.create_index(op.f('ix_food_item_brand'), 'food_item', ['brand'], unique=False)
    op.create_index(op.f('ix_food_item_canonical_id'), 'food_item', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_food_item_id'), 'food_item', ['id'], unique=False)
    op.create_index(op.f('ix_food_item_name'), 'food_item', ['name'], unique=False)
    op.create_table('medication',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('english_name', sa.String(length=255), nullable=True),
    sa.Column('form', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('item_seq', sa.String(length=50), nullable=True),
    sa.Column('valid_term', sa.String(length=100), nullable=True),
    sa.Column('storage_method', sa.String(length=255), nullable=True),
    sa.Column('material_name', sa.Text(), nullable=True),
    sa.Column('license_status', sa.String(length=50), nullable=True),
    sa.Column('license_date', sa.Date(), nullable=True),
    sa.Column('cancel_date', sa.Date(), nullable=True),
    sa.Column('efficacy_group', sa.String(length=100), nullable=True),
    sa.Column('prescription_type', sa.String(length=50), nullable=True),
    sa.Column('source_updated_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_seq')
    )
    op.create_index(op.f('ix_medication_id'), 'medication', ['id'], unique=False)
    op.create_index(op.f('ix_medication_name'), 'medication', ['name'], unique=False)
    op.create_table('medication_ingredient',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('english_name', sa.String(length=255), nullable=True),
    sa.Column('drug_class', sa.String(length=100), nullable=True),
    sa.Column('is_skin_relevant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_ingredient_id'), 'medication_ingredient', ['id'], unique=False)
    op.create_index(op.f('ix_medication_ingredient_name'), 'medication_ingredient', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=60), nullable=False),
    sa.Column('skin_type', sa.String(length=20), nullable=True),
    sa.Column('skin_concerns', sa.JSON(), nullable=True),
    sa.Column('raw_concern_text', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('avg_cycle_length', sa.SmallInteger(), nullable=True),
    sa.Column('cycle_regularity', sa.String(length=20), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('session_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('terms_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('push_token', sa.String(length=200), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gender IN ('남','여')", name='chk_gender'),
    sa.CheckConstraint("skin_type IN ('건성','지성','복합성','민감성','중성')", name='chk_skin_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_id'), 'admin_audit_logs', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pending_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('cosmetic_ingredient_map',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['cosmetic_ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['cosmetic_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id')
    )
    op.create_table('daily_behavior_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('water_intake_ml', sa.SmallInteger(), nullable=True),
    sa.Column('exercise_yn', sa.Boolean(), nullable=True),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('exercise_duration_min', sa.SmallInteger(), nullable=True),
    sa.Column('alcohol_yn', sa.Boolean(), nullable=True),
    sa.Column('smoking_yn', sa.Boolean(), nullable=True),
    sa.Column('custom_behaviors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('sleep_quality BETWEEN 1 AND 5', name='chk_sleep_quality'),
    sa.CheckConstraint('stress_level BETWEEN 1 AND 5', name='chk_stress_level'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_behavior_log_id'), 'daily_behavior_log', ['id'], unique=False)
    op.create_index(op.f('ix_daily_behavior_log_logged_at'), 'daily_behavior_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_daily_behavior_log_user_id'), 'daily_behavior_log', ['user_id'], unique=False)
    op.create_table('diet_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('input_method', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('captured_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('captured_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('captured_location_name', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("input_method IN ('photo','manual')", name='chk_input_method'),
    sa.CheckConstraint("meal_type IN ('아침','점심','저녁','간식')", name='chk_meal_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_log_id'), 'diet_log', ['id'], unique=False)
    op.create_index(op.f('ix_diet_log_logged_at'), 'diet_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_diet_log_user_id'), 'diet_log', ['user_id'], unique=False)
    op.create_table('medication_ingredient_map',
    sa.Column('medication_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['medication_ingredient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('medication_id', 'ingredient_id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_dedupe_key'), 'notification_logs', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_notification_logs_notification_type'), 'notification_logs', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skin_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('skin_reminder_time', sa.Time(), nullable=True),
    sa.Column('skin_reminder_days', sa.JSON(), nullable=True),
    sa.Column('daily_log_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_log_reminder_time', sa.Time(), nullable=True),
    sa.Column('analysis_ready_enabled', sa.Boolean(), nullable=False),
    sa.Column('analysis_complete_enabled', sa.Boolean(), nullable=False),
    sa.Column('inactive_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('inactive_days_threshold', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=True)
    op.create_table('notification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expo_push_token', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_tokens_expo_push_token'), 'notification_tokens', ['expo_push_token'], unique=True)
    op.create_index(op.f('ix_notification_tokens_user_id'), 'notification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('period_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_log_id'), 'period_log', ['id'], unique=False)
    op.create_index(op.f('ix_period_log_user_id'), 'period_log', ['user_id'], unique=False)
    op.create_table('skin_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('masked_photo_url', sa.String(length=500), nullable=True),
    sa.Column('left_photo_url', sa.String(length=500), nullable=True),
    sa.Column('right_photo_url', sa.String(length=500), nullable=True),
    sa.Column('condition_tags', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('quality_check_passed', sa.Boolean(), nullable=True),
    sa.Column('quality_warning', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('overall_score BETWEEN 1 AND 5', name='chk_overall_score'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_log_id'), 'skin_log', ['id'], unique=False)
    op.create_index(op.f('ix_skin_log_logged_at'), 'skin_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_skin_log_user_id'), 'skin_log', ['user_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_social_accounts_provider_user_id')
    )
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_table('user_baseline',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skin_tendency', sa.Text(), nullable=True),
    sa.Column('avg_reaction_delay', sa.Integer(), nullable=True, comment='Reserved; excluded from analysis context until evidence-date inference exists.'),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('last_calibrated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_baseline_user_id')
    )
    op.create_index(op.f('ix_user_baseline_id'), 'user_baseline', ['id'], unique=False)
    op.create_table('user_changepoint',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.Date(), nullable=False),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('changepoint_date', sa.Date(), nullable=True),
    sa.Column('signal', sa.String(length=50), nullable=True),
    sa.Column('factor_key', sa.String(length=100), nullable=True),
    sa.Column('analysis_method', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_method IN ('daily_correlation', 'before_after')", name='chk_analysis_method'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_changepoint_id'), 'user_changepoint', ['id'], unique=False)
    op.create_index('ix_user_changepoint_user_detected', 'user_changepoint', ['user_id', 'detected_at'], unique=False)
    op.create_table('user_cosmetics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['cosmetic_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cosmetics_id'), 'user_cosmetics', ['id'], unique=False)
    op.create_table('user_factor_sensitivity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('factor_type', sa.String(length=20), nullable=False),
    sa.Column('factor_key', sa.String(length=255), nullable=False),
    sa.Column('sensitivity_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("factor_type IN ('ingredient','food','environment','medication','behavior','cosmetic')", name='chk_factor_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'factor_type', 'factor_key', name='uq_user_factor')
    )
    op.create_index(op.f('ix_user_factor_sensitivity_id'), 'user_factor_sensitivity', ['id'], unique=False)
    op.create_index(op.f('ix_user_factor_sensitivity_user_id'), 'user_factor_sensitivity', ['user_id'], unique=False)
    op.create_table('user_location',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.String(length=10), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("location_type IN ('home','work')", name='chk_location_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_location_id'), 'user_location', ['id'], unique=False)
    op.create_index(op.f('ix_user_location_user_id'), 'user_location', ['user_id'], unique=False)
    op.create_table('user_medication',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.BigInteger(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('expected_end_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_medication_id'), 'user_medication', ['id'], unique=False)
    op.create_table('analysis_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skin_log_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('concern_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','processing','done','failed')", name='chk_status'),
    sa.ForeignKeyConstraint(['skin_log_id'], ['skin_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_request_id'), 'analysis_request', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_request_skin_log_id'), 'analysis_request', ['skin_log_id'], unique=False)
    op.create_index(op.f('ix_analysis_request_user_id'), 'analysis_request', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('diet_log_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('diet_log_id', sa.BigInteger(), nullable=False),
    sa.Column('food_item_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_food_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diet_log_id'], ['diet_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_log_item_diet_log_id'), 'diet_log_item', ['diet_log_id'], unique=False)
    op.create_index(op.f('ix_diet_log_item_id'), 'diet_log_item', ['id'], unique=False)
    op.create_table('environment_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', mysql.TINYINT(), nullable=True),
    sa.Column('pm10', sa.SmallInteger(), nullable=True),
    sa.Column('pm25', sa.SmallInteger(), nullable=True),
    sa.Column('uv_index', mysql.TINYINT(), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('diet_log_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("source IN ('app_camera', 'exif', 'manual', 'retroactive')", name='chk_source'),
    sa.ForeignKeyConstraint(['diet_log_id'], ['diet_log.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_log_diet_log_id'), 'environment_log', ['diet_log_id'], unique=False)
    op.create_index(op.f('ix_environment_log_id'), 'environment_log', ['id'], unique=False)
    op.create_index(op.f('ix_environment_log_logged_at'), 'environment_log', ['logged_at'], unique=False)
    op.create_index(op.f('ix_environment_log_user_id'), 'environment_log', ['user_id'], unique=False)
    op.create_table('agent_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('suspicious_items', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent_type IN ('cosmetic','medication','diet','environment','behavior')", name='chk_agent_type'),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_result_id'), 'agent_result', ['id'], unique=False)
    op.create_index(op.f('ix_agent_result_request_id'), 'agent_result', ['request_id'], unique=False)
    op.create_table('analysis_result',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('primary_cause', sa.Text(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('concern_verdicts', sa.JSON(), nullable=True),
    sa.Column('discovered_patterns', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['analysis_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_analysis_result_request_id')
    )
    op.create_index(op.f('ix_analysis_result_id'), 'analysis_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_result_id'), table_name='analysis_result')
    op.drop_table('analysis_result')
    op.drop_index(op.f('ix_agent_result_request_id'), table_name='agent_result')
    op.drop_index(op.f('ix_agent_result_id'), table_name='agent_result')
    op.drop_table('agent_result')
    op.drop_index(op.f('ix_environment_log_user_id'), table_name='environment_log')
    op.drop_index(op.f('ix_environment_log_logged_at'), table_name='environment_log')
    op.drop_index(op.f('ix_environment_log_id'), table_name='environment_log')
    op.drop_index(op.f('ix_environment_log_diet_log_id'), table_name='environment_log')
    op.drop_table('environment_log')
    op.drop_index(op.f('ix_diet_log_item_id'), table_name='diet_log_item')
    op.drop_index(op.f('ix_diet_log_item_diet_log_id'), table_name='diet_log_item')
    op.drop_table('diet_log_item')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_analysis_request_user_id'), table_name='analysis_request')
    op.drop_index(op.f('ix_analysis_request_skin_log_id'), table_name='analysis_request')
    op.drop_index(op.f('ix_analysis_request_id'), table_name='analysis_request')
    op.drop_table('analysis_request')
    op.drop_index(op.f('ix_user_medication_id'), table_name='user_medication')
    op.drop_table('user_medication')
    op.drop_index(op.f('ix_user_location_user_id'), table_name='user_location')
    op.drop_index(op.f('ix_user_location_id'), table_name='user_location')
    op.drop_table('user_location')
    op.drop_index(op.f('ix_user_factor_sensitivity_user_id'), table_name='user_factor_sensitivity')
    op.drop_index(op.f('ix_user_factor_sensitivity_id'), table_name='user_factor_sensitivity')
    op.drop_table('user_factor_sensitivity')
    op.drop_index(op.f('ix_user_cosmetics_id'), table_name='user_cosmetics')
    op.drop_table('user_cosmetics')
    op.drop_index('ix_user_changepoint_user_detected', table_name='user_changepoint')
    op.drop_index(op.f('ix_user_changepoint_id'), table_name='user_changepoint')
    op.drop_table('user_changepoint')
    op.drop_index(op.f('ix_user_baseline_id'), table_name='user_baseline')
    op.drop_table('user_baseline')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_skin_log_user_id'), table_name='skin_log')
    op.drop_index(op.f('ix_skin_log_logged_at'), table_name='skin_log')
    op.drop_index(op.f('ix_skin_log_id'), table_name='skin_log')
    op.drop_table('skin_log')
    op.drop_index(op.f('ix_period_log_user_id'), table_name='period_log')
    op.drop_index(op.f('ix_period_log_id'), table_name='period_log')
    op.drop_table('period_log')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notification_tokens_user_id'), table_name='notification_tokens')
    op.drop_index(op.f('ix_notification_tokens_expo_push_token'), table_name='notification_tokens')
    op.drop_table('notification_tokens')
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_notification_type'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_dedupe_key'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('medication_ingredient_map')
    op.drop_index(op.f('ix_diet_log_user_id'), table_name='diet_log')
    op.drop_index(op.f('ix_diet_log_logged_at'), table_name='diet_log')
    op.drop_index(op.f('ix_diet_log_id'), table_name='diet_log')
    op.drop_table('diet_log')
    op.drop_index(op.f('ix_daily_behavior_log_user_id'), table_name='daily_behavior_log')
    op.drop_index(op.f('ix_daily_behavior_log_logged_at'), table_name='daily_behavior_log')
    op.drop_index(op.f('ix_daily_behavior_log_id'), table_name='daily_behavior_log')
    op.drop_table('daily_behavior_log')
    op.drop_table('cosmetic_ingredient_map')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_admin_audit_logs_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_medication_ingredient_name'), table_name='medication_ingredient')
    op.drop_index(op.f('ix_medication_ingredient_id'), table_name='medication_ingredient')
    op.drop_table('medication_ingredient')
    op.drop_index(op.f('ix_medication_name'), table_name='medication')
    op.drop_index(op.f('ix_medication_id'), table_name='medication')
    op.drop_table('medication')
    op.drop_index(op.f('ix_food_item_name'), table_name='food_item')
    op.drop_index(op.f('ix_food_item_id'), table_name='food_item')
    op.drop_index(op.f('ix_food_item_canonical_id'), table_name='food_item')
    op.drop_index(op.f('ix_food_item_brand'), table_name='food_item')
    op.drop_index(op.f('ix_food_item_barcode'), table_name='food_item')
    op.drop_index(op.f('ix_food_item_api_food_code'), table_name='food_item')
    op.drop_table('food_item')
    op.drop_index(op.f('ix_cosmetic_products_product_name'), table_name='cosmetic_products')
    op.drop_index(op.f('ix_cosmetic_products_normalized_name'), table_name='cosmetic_products')
    op.drop_index(op.f('ix_cosmetic_products_id'), table_name='cosmetic_products')
    op.drop_index(op.f('ix_cosmetic_products_brand'), table_name='cosmetic_products')
    op.drop_table('cosmetic_products')
    op.drop_index(op.f('ix_cosmetic_ingredients_name'), table_name='cosmetic_ingredients')
    op.drop_index(op.f('ix_cosmetic_ingredients_id'), table_name='cosmetic_ingredients')
    op.drop_table('cosmetic_ingredients')
    # ### end Alembic commands ###
